import { Word, Gender } from './types';

export const FRENCH_NOUNS: Word[] = [
  // Skiing
  { id: 'ski-1', french: 'ski', english: 'ski', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-2', french: 'neige', english: 'snow', gender: Gender.Feminine, category: 'Skiing' },
  { id: 'ski-3', french: 'montagne', english: 'mountain', gender: Gender.Feminine, category: 'Skiing' },
  { id: 'ski-4', french: 'piste', english: 'slope/track', gender: Gender.Feminine, category: 'Skiing' },
  { id: 'ski-5', french: 'télésiège', english: 'chairlift', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-6', french: 'gant', english: 'glove', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-7', french: 'bonnet', english: 'beanie/hat', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-8', french: 'combinaison', english: 'ski suit', gender: Gender.Feminine, category: 'Skiing' },
  { id: 'ski-9', french: 'chalet', english: 'chalet', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-10', french: 'flocon', english: 'snowflake', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-11', french: 'avalanche', english: 'avalanche', gender: Gender.Feminine, category: 'Skiing' },
  { id: 'ski-12', french: 'glace', english: 'ice', gender: Gender.Feminine, category: 'Skiing' },
  { id: 'ski-13', french: 'froid', english: 'cold', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-14', french: 'hiver', english: 'winter', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-15', french: 'luge', english: 'sled', gender: Gender.Feminine, category: 'Skiing' },
  { id: 'ski-16', french: 'moniteur', english: 'instructor (male)', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-17', french: 'station', english: 'resort', gender: Gender.Feminine, category: 'Skiing' },
  { id: 'ski-18', french: 'forfait', english: 'ski pass', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-19', french: 'bâton', english: 'stick/pole', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-20', french: 'descente', english: 'descent', gender: Gender.Feminine, category: 'Skiing' },

  // Home
  { id: 'home-1', french: 'maison', english: 'house', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-2', french: 'table', english: 'table', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-3', french: 'chaise', english: 'chair', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-4', french: 'lit', english: 'bed', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-5', french: 'fenêtre', english: 'window', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-6', french: 'porte', english: 'door', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-7', french: 'salon', english: 'living room', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-8', french: 'cuisine', english: 'kitchen', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-9', french: 'canapé', english: 'sofa', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-10', french: 'toit', english: 'roof', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-11', french: 'mur', english: 'wall', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-12', french: 'sol', english: 'floor', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-13', french: 'plafond', english: 'ceiling', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-14', french: 'jardin', english: 'garden', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-15', french: 'chambre', english: 'bedroom', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-16', french: 'salle de bain', english: 'bathroom', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-17', french: 'escalier', english: 'staircase', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-18', french: 'lampe', english: 'lamp', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-19', french: 'tapis', english: 'rug', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-20', french: 'clé', english: 'key', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-21', french: 'verre', english: 'glass', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-22', french: 'assiette', english: 'plate', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-23', french: 'fourchette', english: 'fork', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-24', french: 'couteau', english: 'knife', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-25', french: 'cuillère', english: 'spoon', gender: Gender.Feminine, category: 'Home' },

  // Work
  { id: 'work-1', french: 'bureau', english: 'desk/office', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-2', french: 'ordinateur', english: 'computer', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-3', french: 'réunion', english: 'meeting', gender: Gender.Feminine, category: 'Work' },
  { id: 'work-4', french: 'patron', english: 'boss (male)', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-5', french: 'collègue', english: 'colleague', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-6', french: 'dossier', english: 'file/folder', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-7', french: 'téléphone', english: 'phone', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-8', french: 'entreprise', english: 'company', gender: Gender.Feminine, category: 'Work' },
  { id: 'work-9', french: 'salaire', english: 'salary', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-10', french: 'pause', english: 'break', gender: Gender.Feminine, category: 'Work' },
  { id: 'work-11', french: 'contrat', english: 'contract', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-12', french: 'projet', english: 'project', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-13', french: 'équipe', english: 'team', gender: Gender.Feminine, category: 'Work' },
  { id: 'work-14', french: 'client', english: 'client', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-15', french: 'e-mail', english: 'email', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-16', french: 'clavier', english: 'keyboard', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-17', french: 'écran', english: 'screen', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-18', french: 'imprimante', english: 'printer', gender: Gender.Feminine, category: 'Work' },
  { id: 'work-19', french: 'chaise', english: 'chair', gender: Gender.Feminine, category: 'Work' },
  { id: 'work-20', french: 'emploi', english: 'job', gender: Gender.Masculine, category: 'Work' },

  // Common
  { id: 'common-1', french: 'temps', english: 'time/weather', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-2', french: 'jour', english: 'day', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-3', french: 'année', english: 'year', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-4', french: 'vie', english: 'life', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-5', french: 'homme', english: 'man', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-6', french: 'femme', english: 'woman', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-7', french: 'enfant', english: 'child', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-8', french: 'monde', english: 'world', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-9', french: 'école', english: 'school', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-10', french: 'argent', english: 'money', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-11', french: 'pays', english: 'country', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-12', french: 'ville', english: 'city', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-13', french: 'rue', english: 'street', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-14', french: 'voiture', english: 'car', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-15', french: 'ami', english: 'friend (male)', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-16', french: 'problème', english: 'problem', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-17', french: 'histoire', english: 'story/history', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-18', french: 'idée', english: 'idea', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-19', french: 'eau', english: 'water', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-20', french: 'feu', english: 'fire', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-21', french: 'livre', english: 'book', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-22', french: 'musique', english: 'music', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-23', french: 'film', english: 'movie', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-24', french: 'chose', english: 'thing', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-25', french: 'amour', english: 'love', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-26', french: 'café', english: 'coffee', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-27', french: 'thé', english: 'tea', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-28', french: 'bière', english: 'beer', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-29', french: 'vin', english: 'wine', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-30', french: 'soleil', english: 'sun', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-31', french: 'lune', english: 'moon', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-32', french: 'nuit', english: 'night', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-33', french: 'matin', english: 'morning', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-34', french: 'soir', english: 'evening', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-35', french: 'semaine', english: 'week', gender: Gender.Feminine, category: 'Common' },
];