import { Word, Gender } from './types';

export const FRENCH_NOUNS: Word[] = [
  // --- EXCEPTIONS (The tricky ones) ---
  // Masculine nouns ending in -e (usually feminine ending)
  { id: 'ex-1', french: 'squelette', english: 'skeleton', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-2', french: 'musée', english: 'museum', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-3', french: 'lycée', english: 'high school', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-4', french: 'système', english: 'system', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-5', french: 'problème', english: 'problem', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-6', french: 'modèle', english: 'model', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-7', french: 'groupe', english: 'group', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-8', french: 'programme', english: 'program', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-9', french: 'domaine', english: 'domain/field', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-10', french: 'rôle', english: 'role', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-11', french: 'légume', english: 'vegetable', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-12', french: 'sucre', english: 'sugar', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-13', french: 'beurre', english: 'butter', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-14', french: 'incendie', english: 'fire (disaster)', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-15', french: 'monde', english: 'world', gender: Gender.Masculine, category: 'Exceptions' },
  // Feminine nouns ending in -age (usually masculine ending)
  { id: 'ex-16', french: 'plage', english: 'beach', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-17', french: 'cage', english: 'cage', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-18', french: 'page', english: 'page', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-19', french: 'image', english: 'image', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-20', french: 'rage', english: 'rage', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-21', french: 'nage', english: 'swimming', gender: Gender.Feminine, category: 'Exceptions' },
  // Feminine nouns ending in -eau (usually masculine ending)
  { id: 'ex-22', french: 'peau', english: 'skin', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-23', french: 'eau', english: 'water', gender: Gender.Feminine, category: 'Exceptions' },
  // Feminine nouns not ending in -e
  { id: 'ex-24', french: 'main', english: 'hand', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-25', french: 'fin', english: 'end', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-26', french: 'dent', english: 'tooth', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-27', french: 'forêt', english: 'forest', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-28', french: 'nuit', english: 'night', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-29', french: 'mer', english: 'sea', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-30', french: 'mort', english: 'death', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-31', french: 'tribu', english: 'tribe', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-32', french: 'vertu', english: 'virtue', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-33', french: 'foi', english: 'faith', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-34', french: 'loi', english: 'law', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-35', french: 'maison', english: 'house', gender: Gender.Feminine, category: 'Exceptions' },
  // Masculine words ending in -ion (usually feminine)
  { id: 'ex-36', french: 'avion', english: 'airplane', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-37', french: 'camion', english: 'truck', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-38', french: 'million', english: 'million', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-39', french: 'bastion', english: 'bastion', gender: Gender.Masculine, category: 'Exceptions' },
  // Short words ending in -o (feminine)
  { id: 'ex-40', french: 'radio', english: 'radio', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-41', french: 'moto', english: 'motorcycle', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-42', french: 'photo', english: 'photo', gender: Gender.Feminine, category: 'Exceptions' },
  { id: 'ex-43', french: 'météo', english: 'weather forecast', gender: Gender.Feminine, category: 'Exceptions' },
  // -té ending (usually feminine) but masculine exceptions
  { id: 'ex-44', french: 'côté', english: 'side', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-45', french: 'été', english: 'summer', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-46', french: 'comité', english: 'committee', gender: Gender.Masculine, category: 'Exceptions' },
  { id: 'ex-47', french: 'pâté', english: 'pâté', gender: Gender.Masculine, category: 'Exceptions' },

  // --- SKIING ---
  { id: 'ski-1', french: 'ski', english: 'ski', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-2', french: 'neige', english: 'snow', gender: Gender.Feminine, category: 'Skiing' },
  { id: 'ski-3', french: 'montagne', english: 'mountain', gender: Gender.Feminine, category: 'Skiing' },
  { id: 'ski-4', french: 'piste', english: 'slope/track', gender: Gender.Feminine, category: 'Skiing' },
  { id: 'ski-5', french: 'télésiège', english: 'chairlift', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-6', french: 'gant', english: 'glove', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-7', french: 'bonnet', english: 'beanie/hat', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-8', french: 'combinaison', english: 'ski suit', gender: Gender.Feminine, category: 'Skiing' },
  { id: 'ski-9', french: 'chalet', english: 'chalet', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-10', french: 'flocon', english: 'snowflake', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-11', french: 'avalanche', english: 'avalanche', gender: Gender.Feminine, category: 'Skiing' },
  { id: 'ski-12', french: 'glace', english: 'ice', gender: Gender.Feminine, category: 'Skiing' },
  { id: 'ski-13', french: 'froid', english: 'cold', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-14', french: 'hiver', english: 'winter', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-15', french: 'luge', english: 'sled', gender: Gender.Feminine, category: 'Skiing' },
  { id: 'ski-16', french: 'moniteur', english: 'instructor (male)', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-17', french: 'station', english: 'resort', gender: Gender.Feminine, category: 'Skiing' },
  { id: 'ski-18', french: 'forfait', english: 'ski pass', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-19', french: 'bâton', english: 'stick/pole', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-20', french: 'descente', english: 'descent', gender: Gender.Feminine, category: 'Skiing' },
  { id: 'ski-21', french: 'sommet', english: 'summit', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-22', french: 'vallée', english: 'valley', gender: Gender.Feminine, category: 'Skiing' },
  { id: 'ski-23', french: 'brouillard', english: 'fog', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-24', french: 'glacier', english: 'glacier', gender: Gender.Masculine, category: 'Skiing' },
  { id: 'ski-25', french: 'soleil', english: 'sun', gender: Gender.Masculine, category: 'Skiing' },

  // --- HOME ---
  { id: 'home-1', french: 'table', english: 'table', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-2', french: 'chaise', english: 'chair', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-3', french: 'lit', english: 'bed', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-4', french: 'fenêtre', english: 'window', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-5', french: 'porte', english: 'door', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-6', french: 'salon', english: 'living room', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-7', french: 'cuisine', english: 'kitchen', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-8', french: 'canapé', english: 'sofa', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-9', french: 'toit', english: 'roof', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-10', french: 'mur', english: 'wall', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-11', french: 'sol', english: 'floor', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-12', french: 'plafond', english: 'ceiling', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-13', french: 'jardin', english: 'garden', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-14', french: 'chambre', english: 'bedroom', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-15', french: 'salle de bain', english: 'bathroom', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-16', french: 'escalier', english: 'staircase', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-17', french: 'lampe', english: 'lamp', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-18', french: 'tapis', english: 'rug', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-19', french: 'clé', english: 'key', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-20', french: 'verre', english: 'glass', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-21', french: 'assiette', english: 'plate', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-22', french: 'fourchette', english: 'fork', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-23', french: 'couteau', english: 'knife', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-24', french: 'cuillère', english: 'spoon', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-25', french: 'miroir', english: 'mirror', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-26', french: 'rideau', english: 'curtain', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-27', french: 'balcon', english: 'balcony', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-28', french: 'garage', english: 'garage', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-29', french: 'cheminée', english: 'chimney/fireplace', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-30', french: 'serviette', english: 'towel', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-31', french: 'drap', english: 'sheet', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-32', french: 'couette', english: 'duvet', gender: Gender.Feminine, category: 'Home' },
  { id: 'home-33', french: 'oreiller', english: 'pillow', gender: Gender.Masculine, category: 'Home' },
  { id: 'home-34', french: 'savon', english: 'soap', gender: Gender.Masculine, category: 'Home' },

  // --- WORK ---
  { id: 'work-1', french: 'bureau', english: 'desk/office', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-2', french: 'ordinateur', english: 'computer', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-3', french: 'réunion', english: 'meeting', gender: Gender.Feminine, category: 'Work' },
  { id: 'work-4', french: 'patron', english: 'boss (male)', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-5', french: 'collègue', english: 'colleague', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-6', french: 'dossier', english: 'file/folder', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-7', french: 'téléphone', english: 'phone', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-8', french: 'entreprise', english: 'company', gender: Gender.Feminine, category: 'Work' },
  { id: 'work-9', french: 'salaire', english: 'salary', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-10', french: 'pause', english: 'break', gender: Gender.Feminine, category: 'Work' },
  { id: 'work-11', french: 'contrat', english: 'contract', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-12', french: 'projet', english: 'project', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-13', french: 'équipe', english: 'team', gender: Gender.Feminine, category: 'Work' },
  { id: 'work-14', french: 'client', english: 'client', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-15', french: 'e-mail', english: 'email', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-16', french: 'clavier', english: 'keyboard', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-17', french: 'écran', english: 'screen', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-18', french: 'imprimante', english: 'printer', gender: Gender.Feminine, category: 'Work' },
  { id: 'work-19', french: 'emploi', english: 'job', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-20', french: 'souris', english: 'mouse', gender: Gender.Feminine, category: 'Work' },
  { id: 'work-21', french: 'rapport', english: 'report', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-22', french: 'carrière', english: 'career', gender: Gender.Feminine, category: 'Work' },
  { id: 'work-23', french: 'succès', english: 'success', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-24', french: 'échec', english: 'failure', gender: Gender.Masculine, category: 'Work' },
  { id: 'work-25', french: 'agrafeuse', english: 'stapler', gender: Gender.Feminine, category: 'Work' },

  // --- COMMON ---
  { id: 'common-1', french: 'temps', english: 'time/weather', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-2', french: 'jour', english: 'day', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-3', french: 'année', english: 'year', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-4', french: 'vie', english: 'life', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-5', french: 'homme', english: 'man', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-6', french: 'femme', english: 'woman', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-7', french: 'enfant', english: 'child', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-8', french: 'école', english: 'school', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-9', french: 'argent', english: 'money', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-10', french: 'pays', english: 'country', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-11', french: 'ville', english: 'city', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-12', french: 'rue', english: 'street', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-13', french: 'voiture', english: 'car', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-14', french: 'ami', english: 'friend (male)', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-15', french: 'histoire', english: 'story/history', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-16', french: 'idée', english: 'idea', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-17', french: 'feu', english: 'fire', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-18', french: 'livre', english: 'book', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-19', french: 'musique', english: 'music', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-20', french: 'film', english: 'movie', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-21', french: 'chose', english: 'thing', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-22', french: 'amour', english: 'love', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-23', french: 'café', english: 'coffee', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-24', french: 'thé', english: 'tea', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-25', french: 'bière', english: 'beer', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-26', french: 'vin', english: 'wine', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-27', french: 'lune', english: 'moon', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-28', french: 'matin', english: 'morning', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-29', french: 'soir', english: 'evening', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-30', french: 'semaine', english: 'week', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-31', french: 'chien', english: 'dog', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-32', french: 'chat', english: 'cat', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-33', french: 'oiseau', english: 'bird', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-34', french: 'fleur', english: 'flower', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-35', french: 'arbre', english: 'tree', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-36', french: 'ciel', english: 'sky', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-37', french: 'nuage', english: 'cloud', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-38', french: 'pluie', english: 'rain', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-39', french: 'vent', english: 'wind', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-40', french: 'rêve', english: 'dream', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-41', french: 'bonheur', english: 'happiness', gender: Gender.Masculine, category: 'Common' },
  { id: 'common-42', french: 'liberté', english: 'freedom', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-43', french: 'paix', english: 'peace', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-44', french: 'guerre', english: 'war', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-45', french: 'couleur', english: 'color', gender: Gender.Feminine, category: 'Common' },
  { id: 'common-46', french: 'peur', english: 'fear', gender: Gender.Feminine, category: 'Common' },
];